# Generated by Django 3.2.5 on 2022-03-19 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('cour_id', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='课程ID')),
                ('cour_name', models.CharField(max_length=30, verbose_name='课程名')),
                ('credit', models.CharField(max_length=30, verbose_name='学分')),
                ('period', models.CharField(max_length=30, verbose_name='学时')),
            ],
            options={
                'db_table': 'course_data',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('stu_id', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='学生ID')),
                ('stu_name', models.CharField(max_length=30, verbose_name='学生名')),
                ('stu_sex', models.CharField(default='男', max_length=20, verbose_name='性别')),
                ('stu_class', models.CharField(max_length=20, verbose_name='院系')),
                ('stu_major', models.CharField(max_length=30, verbose_name='专业')),
            ],
            options={
                'db_table': 'student_data',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, verbose_name='用户名')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'user_data',
            },
        ),
    ]
